---
title: "US Tilapia Imports"
output: html_document
date: "2025-08-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(janitor)
```
```{r}
us_tilapia_imports <- read_csv(here::here("data", "us_tilapia_imports.csv"))
```
```{r}
tilapia_long <- us_tilapia_imports %>% 
  pivot_longer(!country, names_to = "year", values_to = "tilapia")
 
tilapia_long$year <- as.numeric(tilapia_long$year)


```

```{r}
yearly_tilapia_tot <- tilapia_long %>%  dplyr::group_by(year) %>% summarize(sum_tilapia = sum(tilapia, na.rm = TRUE))


```

```{r}
tilapia_imports <- ggplot(yearly_tilapia_tot, aes(year, sum_tilapia)) +
  geom_point() +
  labs(title = "US Imports of Tilapia",
       x = "Year",
       y = "Imported Tilapia (thousands of lbs)")
tilapia_imports
```

```{r}
ggsave(here::here("figs", "tilapia_imports.png"))
```

```{r}
central_amer <- tilapia_long %>% 
  subset(country == "Honduras" | country == "Mexico" | country == "Costa Rica" | country == "Ecuador")
```

```{r}
cen_am_imports <- ggplot(central_amer, aes(year, tilapia, color = country)) +
  geom_point() +
  scale_color_manual(values = c("darkblue", "lightpink", "lightgreen", "orange")) +
  facet_wrap(~country) +
  theme_minimal() +
    labs(title = "US Imports of Tilapia from Central America",
       x = "Year",
       y = "Imported Tilapia (thousands of lbs)")

cen_am_imports
```
```{r}
ggsave(here::here("figs", "cen_am_imports.png"), height = 5, width = 8)
```

